### PR TITLE
Feature#5/folder structure

### LINKED ISSUE #5: Create folder structure based on good practice article
https://cheesecakelabs.com/blog/efficient-way-structure-react-native-projects/

### PR DESCRIPTION
**Pull request by jjcr11**
# Description
We createad a structure folder to have organized the project following the next link: https://cheesecakelabs.com/blog/efficient-way-structure-react-native-projects/

We deleted the App.js from root directory in order to work with the src/index.js file
 
 # Testing
N/A

  ## Screenshots 
image

### CODE REVIEW

**Comment by vmagana3** [comment]
That structure is OK, in order to improve scalability, changes and features  that may be required to be changed in the future

**Comment by HRuvalcabaP** [comment]
It's fine, but I don't think it was necessary to remove App.jss

**Comment by sebasdrk17** [comment]
It looks fine, but as @HRuvalcabaP said, i don't think you needed to delete the App.js file, but it looks great!

**Review by sebasdrk17 — APPROVED** [review]
Looks great!

**Review by tovl1 — APPROVED** [review]
It's good, but no necessary to remove app.js

**Comment by alcamk** [comment]
Looks fine but in past projects, we need the App.js file, and maybe in the path you will change folders, but it's okay.

**Review by Ing-Heber — APPROVED** [review]
Nice work!! I liked the folder description! but please keep in mind that you will probably need App.js as the provided link recommends and also think about saving only general styles in styles folder.

**Review by JordiGN — APPROVED** [review]
As the last time, great description, it is a good practice for documentation, as the other coders and mentors said before, I'm not sure about deleting App.js, anyway, good job!

**Review by LeyaimMagma — APPROVED** [review]

**Pull request merged**
